# Generated by Django 5.2.6 on 2025-12-12 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('autor', models.CharField(default='Descubre Curicó', max_length=120)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='articulos/portadas/')),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='PUBLISHED', max_length=12)),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-publicado_en'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('SUBTITLE', 'Subtítulo'), ('IMAGE', 'Imagen'), ('URL', 'Enlace'), ('YOUTUBE', 'YouTube'), ('VIDEO', 'Video (MP4/URL directa)')], default='TEXT', max_length=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/bloques/')),
                ('pie_de_foto', models.CharField(blank=True, max_length=200)),
                ('estilo_imagen', models.CharField(choices=[('default', 'Default'), ('rounded', 'Bordes redondeados'), ('wide', 'Ancho completo'), ('shadow', 'Sombra')], default='default', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='appadmincontenido.articulo')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='appadmincontenido.categoria'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='appadmincontenido.articulo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('autor', models.CharField(default='Descubre Curicó', max_length=120)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='articulos/portadas/')),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='PUBLISHED', max_length=12)),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='appadmincontenido.categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-publicado_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('SUBTITLE', 'Subtítulo'), ('IMAGE', 'Imagen'), ('URL', 'Enlace'), ('YOUTUBE', 'YouTube'), ('VIDEO', 'Video (MP4/URL directa)')], default='TEXT', max_length=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/bloques/')),
                ('pie_de_foto', models.CharField(blank=True, max_length=200)),
                ('estilo_imagen', models.CharField(choices=[('default', 'Default'), ('rounded', 'Bordes redondeados'), ('wide', 'Ancho completo'), ('shadow', 'Sombra')], default='default', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='appadmincontenido.noticia')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reportaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('autor', models.CharField(default='Descubre Curicó', max_length=120)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='articulos/portadas/')),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='PUBLISHED', max_length=12)),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='appadmincontenido.categoria')),
            ],
            options={
                'verbose_name': 'Reportaje',
                'verbose_name_plural': 'Reportajes',
                'ordering': ['-publicado_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueReportaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('SUBTITLE', 'Subtítulo'), ('IMAGE', 'Imagen'), ('URL', 'Enlace'), ('YOUTUBE', 'YouTube'), ('VIDEO', 'Video (MP4/URL directa)')], default='TEXT', max_length=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportajes/bloques/')),
                ('pie_de_foto', models.CharField(blank=True, max_length=200)),
                ('estilo_imagen', models.CharField(choices=[('default', 'Default'), ('rounded', 'Bordes redondeados'), ('wide', 'Ancho completo'), ('shadow', 'Sombra')], default='default', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('reportaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='appadmincontenido.reportaje')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
