# Generated by Django 5.2.6 on 2025-12-12 18:40

import appsocios.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion_completa', models.TextField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.URLField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empresas/fotos/')),
                ('latitud', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitud', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('abreviatura', models.CharField(max_length=4)),
                ('capital', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'Rubro',
                'ordering': ['nombre_rubro'],
            },
        ),
        migrations.CreateModel(
            name='TipoComercializacion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de comercialización',
                'verbose_name_plural': 'Tipos de comercialización',
                'db_table': 'TipoComercializacion',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_1_descuento_comercializacion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='¿Ofrece descuento por comercialización?')),
                ('pregunta_2_tipo_descuento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descuento o beneficio (detallado) Ej: Descuento en tour, Descuento en productos, Descuento en hospedaje; etc.')),
                ('pregunta_2_porcentaje', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='¿Qué porcentaje % de descuento ofrece? (0% al 100%, puede escribir el número de porcentaje directamente en el signo %) ')),
                ('pregunta_3_valor_empresa', models.TextField(blank=True, null=True, verbose_name='¿Qué valor aportará tu empresa tanto al gremio como a la ciudad, y cuál es tu visión sobre la colaboración para lograrlo?')),
                ('pregunta_4_empresa_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Qué empresa de Descubre Curicó tiene referencia y apoya tu incorporación?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='appsocios.empresa')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'Encuesta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=64)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='appsocios.provincia')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comunas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='appsocios.region'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(blank=True, db_column='rubro_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='appsocios.rubro'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('socio_id', models.AutoField(primary_key=True, serialize=False)),
                ('socio_rut', models.CharField(max_length=10, unique=True, validators=[appsocios.models.validar_run], verbose_name='Rut')),
                ('socio_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('socio_apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('socio_apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('socio_celular', models.CharField(max_length=12, verbose_name='Teléfono Celular')),
                ('socio_fijo', models.CharField(max_length=12, verbose_name='Teléfono Fijo')),
                ('socio_correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('socio_direccion', models.CharField(max_length=256, verbose_name='Dirección')),
                ('socio_numero', models.CharField(max_length=256, verbose_name='Número de Casa/Torre/Piso')),
                ('socio_estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('socio_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsocios.comuna', verbose_name='Comuna')),
                ('socio_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsocios.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'Socio',
                'ordering': ['socio_nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='socio',
            field=models.ForeignKey(blank=True, db_column='socio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='appsocios.socio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_comercializacion',
            field=models.ForeignKey(blank=True, db_column='tipo_comercializacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='appsocios.tipocomercializacion'),
        ),
    ]
