# Generated by Django 5.2 on 2025-12-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0002_socio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='socio_contraseña',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña'),
        ),
    ]
