# Generated by Django 5.2 on 2025-12-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0003_socio_socio_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='comuna',
            field=models.ForeignKey(blank=True, db_column='comuna_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='appsocios.comuna'),
        ),
    ]
