# Generated by Django 5.2.8 on 2025-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0004_alter_empresa_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='socio_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
