# Generated by Django 5.2.6 on 2025-12-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0005_socio_socio_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='encuesta_respondida',
            field=models.BooleanField(default=False, verbose_name='Encuesta Respondida'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado Solicitud'),
        ),
    ]
