# Generated by Django 5.2.6 on 2025-12-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0006_empresa_encuesta_respondida_empresa_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
