# Generated by Django 5.2.6 on 2025-12-26 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocios', '0007_empresa_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activa'),
        ),
    ]
